grabdish/ingress/nginx/ingress-nginx-helm-values4oci.yaml, grabdish/inventory-helidon/undeploy.sh, grabdish/k6/test.sh
Primary fix: Changed the OCI LB creation statement in the Ingress controller to fix in 100Mbps shape.
Secondary items:
- return with inventory helidon service deletion during undeploy
- adjust k6 test path
=> Change from OCI LB Flex to 100Mbps

grabdish/utils/main-setup.sh, grabdish/utils/main-test.sh
And commented out tracing tests because they have changed and moved to observability.
=> Support Live Labs with 5 Digit Reservation ID

grabdish/inventory-helidon-se/Dockerfile, grabdish/inventory-helidon/Dockerfile, grabdish/inventory-helidon/pom.xml, grabdish/inventory-python/Dockerfile, grabdish/inventory-quarkus/pom.xml, grabdish/order-helidon/Dockerfile, grabdish/order-helidon/pom.xml, grabdish/utils/java-builds.sh, grabdish/utils/non-java-builds.sh, grabdish/utils/polyglot-test.sh
Reverted switch to Graal docker image and reorganized non-java builds to minimize runtime.
=> Slow build fix

grabdish/inventory-go/Dockerfile
libnsl has been updated and we need to update our symlink
=> update inventory-go build

code-teq/plsqlTeq/cleanupTEQ.sql, code-teq/plsqlTeq/createTEQ.sql, code-teq/plsqlTeq/dequeueTEQ.sql, code-teq/plsqlTeq/enqueueTEQ.sql
=> WIP: Update sample code for TEQ site

cloudbank/cloudbank-react-native/README.md, cloudbank/cloudbank-react-native/android/app/src/main/AndroidManifest.xml, cloudbank/cloudbank-react-native/android/gradle/wrapper/gradle-wrapper.properties, cloudbank/cloudbank-react-native/android/gradlew, cloudbank/cloudbank-react-native/components/Accounts/Accounts.js, cloudbank/cloudbank-react-native/package.json
Some small updates to make sure it is runnable from the new repo and update some deps.
=> CloudBank react-native updates

cloudbank/cloudbank-react-native/package.json
=> Fix dep versions

workshops/txeventq-kafka/cloud-setup/cmd/txeventq-add-topic, workshops/txeventq-kafka/cloud-setup/cmd/txeventq-dequeue, workshops/txeventq-kafka/cloud-setup/confluent-kafka/kafka-setup.sh, workshops/txeventq-kafka/cloud-setup/utils/main-setup.sh, workshops/txeventq-kafka/kafka-connect-txeventq/setup-kafka2txeventq-connect.sh
Fix failure to create sink connector when typing wrong DB password #484 and other minor adjustments.
=> Fix issue 484:  fail to create sink connector if issue wrong DB password #484

workshops/txeventq-kafka/cloud-setup/cmd/bash-cleanup, workshops/txeventq-kafka/cloud-setup/cmd/kafka-undeploy, workshops/txeventq-kafka/cloud-setup/cmd/teardown, workshops/txeventq-kafka/cloud-setup/confluent-kafka/kafka-setup.sh, workshops/txeventq-kafka/cloud-setup/database/oracle_db_setup_password.sh, workshops/txeventq-kafka/cloud-setup/env.sh, workshops/txeventq-kafka/cloud-setup/java/graalvm-install.sh, workshops/txeventq-kafka/cloud-setup/java/graalvm-uninstall.sh, workshops/txeventq-kafka/cloud-setup/utils/bash-setup.sh, workshops/txeventq-kafka/cloud-setup/utils/main-setup.sh
This PR handle Patch Update #492
=> PR TxEventQinOracleDB v1.1.2 Patch Update

docs-source/spring/content/platform/_index.md
=> missing links

docs-source/mbaas/content/_index.md, docs-source/mbaas/content/firebase-emulation/extra.md, docs-source/spring/content/sample-apps/_index.md
=> Doc updates

docs-source/mbaas/content/firebase-emulation/extra.md, docs-source/mbaas/content/firebase-emulation/friendly-eats.md
=> fix firebase links

docs-source/mbaas/config.toml, docs-source/mbaas/themes/hugo-geekdoc/layouts/partials/page-header.html, docs-source/spring/config.toml, docs-source/spring/themes/hugo-geekdoc/layouts/partials/page-header.html
=> add analytics

docs-source/spring/content/cluster-access/_index.md, docs-source/spring/content/observability/metrics/_index.md, docs-source/spring/content/observability/tracing/_index.md, docs-source/spring/content/platform/conductor/_index.md, docs-source/spring/content/platform/eureka/_index.md, docs-source/spring/content/platform/spring-admin/_index.md, docs-source/spring/content/sample-apps/_index.md, docs-source/spring/content/security/_index.md, docs-source/spring/content/setup/_index.md, mbaas-developer-preview/walking-history/App.js
=> Doc updates - post xmas review

mbaas-developer-preview/sample-spring-apps/aqjms_sample/pom.xml, spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/pom.xml, spring/oracle-spring-boot-starters/oracle-spring-boot-starter-ucp/pom.xml, spring/oracle-spring-boot-starters/pom.xml
update the maven coordinates to prepare for publishing to central
=> fix maven coords

spring/oracle-spring-boot-starters/THIRD_PARTY_LICENSES.txt, spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/THIRD_PARTY_LICENSES.txt, spring/oracle-spring-boot-starters/oracle-spring-boot-starter-ucp/THIRD_PARTY_LICENSES.txt
=> add TPL files

docs-source/spring/content/release-notes/_index.md, docs-source/spring/data/menu/main.yaml
=> Add release notes page

grabdish/config/db/2db-atp/apply/03-db1-aq-create-queues.sql, grabdish/config/db/2db-atp/apply/04-db2-aq-create-queues.sql, grabdish/config/db/params.env
Fixes workshop install failure after ADB wallet change
=> SSL_SERVER_CERT removed

docs-source/spring/content/development/cli/_index.md
We are updating CLI documentation to adhere to v0.3.0.
=> Update CLI documentation.

spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/LICENSE.txt, spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/THIRD_PARTY_LICENSES.txt, spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/oracle-spring-boot-starter-wallet-2.7.7.pom, spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/pom.xml, spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starters-2.7.7.pom, spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/LICENSE.txt, spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/THIRD_PARTY_LICENSES.txt, spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/oracle-spring-boot-starter-wallet-3.0.2.pom, spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/pom.xml, spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starters-3.0.2.pom
Initial commit of Spring Boot Starter Wallet (2.7.7 and 3.0.2)
=> Spring Boot Starter Wallet

docs-source/spring/content/blogs/_index.md
=> blog update

cloudbank-v2/spring-apps/account/pom.xml, cloudbank-v2/spring-apps/account/src/main/java/com/example/accounts/controller/AccountController.java, cloudbank-v2/spring-apps/account/src/main/resources/application.yaml, cloudbank-v2/spring-apps/creditscore/pom.xml, cloudbank-v2/spring-apps/creditscore/src/main/java/com/example/creditscore/controller/CreditScoreController.java, cloudbank-v2/spring-apps/creditscore/src/main/resources/application.yaml, cloudbank-v2/spring-apps/customer/pom.xml, cloudbank-v2/spring-apps/customer/src/main/resources/application.yaml, cloudbank-v2/spring-apps/transfer/pom.xml, cloudbank-v2/spring-apps/transfer/src/main/java/com/example/transfer/TransferService.java, cloudbank-v2/spring-apps/transfer/src/main/resources/application.yaml
PR includes:
- Spring Boot update to 2.7.12
- pom.xml cleanups
- Adding dependencies for Grafana
- Minor fixes
=> Grafana fixes, version upgrades, spring starters

cloudbank-v2/spring-apps/customer/pom.xml, cloudbank-v2/spring-apps/customer/src/main/resources/application.yaml, cloudbank-v2/spring-apps/transfer/src/main/java/com/example/transfer/TransferService.java
Changed to use Spring Starter and typo in `pom.xml`
=> Spring starter update and typo

docs-source/spring/content/platform/vault/_index.md, docs-source/spring/content/platform/vscode-plugin/_index.md
=> Incorporated several edits.

docs-source/spring/content/cluster-access/_index.md, docs-source/spring/content/database/_index.md, docs-source/spring/content/observability/_index.md, docs-source/spring/content/observability/metrics/_index.md, docs-source/spring/content/observability/tracing/_index.md, docs-source/spring/content/release-notes/_index.md, docs-source/spring/content/security/_index.md, docs-source/spring/content/uninstall/_index.md
=> Incorporated many edits.

docs-source/spring/content/cluster-access/_index.md, docs-source/spring/content/database/_index.md, docs-source/spring/content/development/cli/_index.md, docs-source/spring/content/observability/metrics/_index.md, docs-source/spring/content/observability/tracing/_index.md, docs-source/spring/content/on-premises/_index.md, docs-source/spring/content/on-premises/ol8/_index.md, docs-source/spring/content/platform/apigw/_index.md, docs-source/spring/content/platform/spring-admin/_index.md, docs-source/spring/content/platform/vault/_index.md, docs-source/spring/content/platform/vscode-plugin/_index.md, docs-source/spring/content/release-notes/_index.md, docs-source/spring/content/security/_index.md, docs-source/spring/content/uninstall/_index.md
=> Incorporated many edits (rhonda_072923_1)

docs-source/mbaas/content/_index.md, docs-source/mbaas/content/azure/_index.md, docs-source/mbaas/content/getting-started/_index.md, docs-source/mbaas/content/getting-started/objects.md, docs-source/mbaas/content/on-premises/_index.md, docs-source/mbaas/content/on-premises/macos_ventura/_index.md, docs-source/mbaas/content/on-premises/ol8/_index.md, docs-source/mbaas/content/setup/_index.md
=> Incorporated many edits (rhonda_072923_2).

docs-source/mbaas/content/cluster-access/_index.md, docs-source/mbaas/content/dashboard/_index.md, docs-source/mbaas/content/database/_index.md, docs-source/mbaas/content/firebase-emulation/_index.md, docs-source/mbaas/content/firebase-emulation/extra.md, docs-source/mbaas/content/firebase-emulation/friendly-eats.md, docs-source/mbaas/content/firebase-emulation/scope.md, docs-source/mbaas/content/getting-started/identity.md, docs-source/mbaas/content/release-notes/_index.md, docs-source/mbaas/content/sample-apps/_index.md, docs-source/mbaas/content/sample-apps/walking-history/_index.md, docs-source/mbaas/content/uninstall/_index.md
=> Incorporated many edits (rhonda_073023_1).

docs-source/mbaas/content/_index.md, docs-source/mbaas/content/azure/_index.md, docs-source/mbaas/content/cluster-access/_index.md, docs-source/mbaas/content/dashboard/_index.md, docs-source/mbaas/content/database/_index.md, docs-source/mbaas/content/firebase-emulation/_index.md, docs-source/mbaas/content/firebase-emulation/extra.md, docs-source/mbaas/content/firebase-emulation/friendly-eats.md, docs-source/mbaas/content/firebase-emulation/scope.md, docs-source/mbaas/content/getting-started/_index.md, docs-source/mbaas/content/getting-started/dashboard.md, docs-source/mbaas/content/getting-started/identity.md, docs-source/mbaas/content/getting-started/objects.md, docs-source/mbaas/content/on-premises/_index.md, docs-source/mbaas/content/on-premises/macos_ventura/_index.md, docs-source/mbaas/content/on-premises/ol8/_index.md, docs-source/mbaas/content/release-notes/_index.md, docs-source/mbaas/content/sample-apps/_index.md, docs-source/mbaas/content/sample-apps/walking-history/_index.md, docs-source/mbaas/content/setup/_index.md, docs-source/mbaas/content/uninstall/_index.md
=> Incorporated several edits (rhonda_080123_1).

docs-source/mbaas/content/setup/_index.md, docs-source/spring/content/_index.md, docs-source/spring/content/azure/_index.md, docs-source/spring/content/cluster-access/_index.md, docs-source/spring/content/database/_index.md, docs-source/spring/content/development/cli/_index.md, docs-source/spring/content/getting-started/_index.md, docs-source/spring/content/observability/_index.md, docs-source/spring/content/observability/metrics/_index.md, docs-source/spring/content/observability/tracing/_index.md, docs-source/spring/content/on-premises/_index.md, docs-source/spring/content/on-premises/macos_ventura/_index.md, docs-source/spring/content/on-premises/ol8/_index.md, docs-source/spring/content/platform/_index.md, docs-source/spring/content/platform/apigw/_index.md, docs-source/spring/content/platform/conductor/_index.md, docs-source/spring/content/platform/config/_index.md, docs-source/spring/content/platform/eureka/_index.md, docs-source/spring/content/platform/spring-admin/_index.md, docs-source/spring/content/platform/vault/_index.md, docs-source/spring/content/platform/vscode-plugin/_index.md, docs-source/spring/content/release-notes/_index.md, docs-source/spring/content/sample-apps/_index.md, docs-source/spring/content/security/_index.md, docs-source/spring/content/setup/_index.md, docs-source/spring/content/uninstall/_index.md
=> Incorporated several review edits (rhonda_080223_1)

cloudbank-v2/spring-apps-spring3/pom.xml
=> Bug fixes in in CBV2 SB3

docs-source/spring/content/development/cli/_index.md
Doc updates for 1.0 release (CLI documentation)
=> Doc updates for 1.0 release

docs-source/spring/content/platform/config/_index.md, docs-source/spring/data/menu/main.yaml
=> Config server doc updates

cloudbank-v3/spring-apps-spring3/account/pom.xml, cloudbank-v3/spring-apps-spring3/checks/pom.xml, cloudbank-v3/spring-apps-spring3/customer/pom.xml, cloudbank-v3/spring-apps-spring3/pom.xml, cloudbank-v3/spring-apps-spring3/testrunner/pom.xml, cloudbank-v3/spring-apps-spring3/transfer/pom.xml
POM file updates (cleanup and versions)
=> POM file updates (cleanup and versions)

cloudbank-v3/spring-apps-spring3/README.md, cloudbank-v3/spring-apps-spring3/customer/src/main/resources/application.yaml
Updated README and fixed customer log problem for Grafana
=> Updated README and customer

cloudbank-v3/spring-apps-spring3/account/pom.xml, cloudbank-v3/spring-apps-spring3/checks/pom.xml, cloudbank-v3/spring-apps-spring3/creditscore/pom.xml, cloudbank-v3/spring-apps-spring3/customer/pom.xml, cloudbank-v3/spring-apps-spring3/testrunner/pom.xml, cloudbank-v3/spring-apps-spring3/transfer/pom.xml
Remove of NIB build I pom.xml files. CLI and GraalVM backend isn't ready
=> Remove of NIB build in pom.xml files

cloudbank-v3/spring-apps-spring3/README.md
=> Update to readme

docs-source/spring/content/release-notes/_index.md
=> Release Notes

docs-source/spring/content/platform/config/_index.md
Updates that I for got yo push before the recent docs build.
=> Update to Config Server docs

docs-source/spring/content/development/_index.md, docs-source/spring/content/development/project.md, docs-source/spring/content/development/setup.md, docs-source/spring/data/menu/main.yaml
This PR adds documentation for the recommended project structure, dependencies and application settings for various scenarios, to take advantage of the built-in platform services.
=> Add documentation of recommended settings and dependencies

docs-source/spring/content/development/cli/_index.md
=> fixed deploy command too long

docs-source/spring/content/security/azn-server/_index.md
Added changeRole documentation
=> Added changeRole documentation

docs-source/spring/content/development/project.md, docs-source/spring/content/platform/config/_index.md
Project structure and cfg server update
=> Project structure and cfg server update

docs-source/spring/content/development/cli/_index.md
an example deploying a graalvm native microservice
=> Update _index.md of oractl 

cloudbank-v32/account/src/main/resources/application.yaml, cloudbank-v32/checks/src/main/resources/application.yaml, cloudbank-v32/creditscore/src/main/resources/application.yaml, cloudbank-v32/customer/src/main/resources/application.yaml, cloudbank-v32/pom.xml, cloudbank-v32/testrunner/src/main/resources/application.yaml, cloudbank-v32/transfer/src/main/resources/application.yaml
=> Tracing updates

cloudbank-v32/account/pom.xml, cloudbank-v32/account/src/main/java/com/example/accounts/AccountsApplication.java, cloudbank-v32/account/src/main/java/com/example/accounts/services/AccountTransferDAO.java, cloudbank-v32/account/src/main/java/com/example/accounts/services/DepositService.java, cloudbank-v32/account/src/main/resources/application.yaml, cloudbank-v32/checks/pom.xml, cloudbank-v32/checks/src/main/resources/application.yaml, cloudbank-v32/creditscore/pom.xml, cloudbank-v32/creditscore/src/main/resources/application.yaml, cloudbank-v32/customer/pom.xml, cloudbank-v32/customer/src/main/resources/application.yaml, cloudbank-v32/pom.xml, cloudbank-v32/testrunner/pom.xml, cloudbank-v32/testrunner/src/main/resources/application.yaml, cloudbank-v32/transfer/pom.xml, cloudbank-v32/transfer/src/main/java/com/example/transfer/TransferService.java, cloudbank-v32/transfer/src/main/resources/application.yaml
CloudBank 32 tracking using OTEL
=> CloudBank 32 tracking using OTEL and fixes

cloudbank-v32/account/pom.xml, cloudbank-v32/customer/pom.xml, cloudbank-v32/customer32/pom.xml, cloudbank-v32/pom.xml
=> version upgrades

cloudbank-v32/README.md, cloudbank-v32/apisix-routes/create-accounts-route.sh, cloudbank-v32/apisix-routes/create-all-routes.sh, cloudbank-v32/apisix-routes/create-customer-route.sh, cloudbank-v32/apisix-routes/create-customer32-route.sh, cloudbank-v32/apisix-routes/create-testrunner-route.sh, cloudbank-v32/apisix-routes/create-transfer-route.sh
Fixes for OTEL, updated README to use instead of tunnels APISIX
=> Fixes for OTEL, updated README to use instead of tunnels APISIX

docs-source/spring/content/development/cli/_index.md, docs-source/spring/content/on-premises/_index.md, docs-source/spring/content/on-premises/macos_ventura/_index.md, docs-source/spring/content/on-premises/ol8/_index.md
=> Correct link to oractl

cloudbank-v32/customer32-mongo/README.md, cloudbank-v32/customer32-mongo/checkstyle/checkstyle.xml, cloudbank-v32/customer32-mongo/checkstyle/suppressions.xml, cloudbank-v32/customer32-mongo/dependency-check/suppressions.xml, cloudbank-v32/customer32-mongo/pom.xml, cloudbank-v32/customer32-mongo/src/main/java/com/example/customer32mongo/CustomerMongoApplication.java, cloudbank-v32/customer32-mongo/src/main/java/com/example/customer32mongo/config/AppConfig.java, cloudbank-v32/customer32-mongo/src/main/java/com/example/customer32mongo/controller/CustomerController.java, cloudbank-v32/customer32-mongo/src/main/java/com/example/customer32mongo/model/Customer.java, cloudbank-v32/customer32-mongo/src/main/java/com/example/customer32mongo/repository/CustomerRepository.java, cloudbank-v32/customer32-mongo/src/main/java/com/example/customer32mongo/service/CustomerService.java, cloudbank-v32/customer32-mongo/src/main/resources/application.yaml
This PR adds an example of using Spring Data MongoDB and the Oracle Database MongoDB API by reimplementing the customer32 service using the MongoDB API. 
See the included README for more details.
=> add a mongodb api sample

docs-source/spring/content/azure/_index.md, docs-source/spring/content/development/cli/_index.md, docs-source/spring/content/platform/vscode-plugin/_index.md, docs-source/spring/content/setup/_index.md, docs-source/spring/content/support/_index.md, docs-source/spring/data/menu/main.yaml, docs-source/spring/themes/hugo-geekdoc/i18n/en.yaml
Doc updates (support and fixes)
=> Doc updates (support and fixes)

docs-source/spring/content/platform/conductor/_index.md
Fixes #845 - update the links for Conductor OSS documentation
=> Update Conductor Docs links

cloudbank-v32/apisix-routes/create-accounts-route.sh, cloudbank-v32/apisix-routes/create-creditscore-route.sh, cloudbank-v32/apisix-routes/create-customer-route.sh, cloudbank-v32/apisix-routes/create-customer32-route.sh, cloudbank-v32/apisix-routes/create-testrunner-route.sh, cloudbank-v32/apisix-routes/create-transfer-route.sh
This PR fixes the Prometheus problem in Cloudbank, fix needs to go into OBaaS as well. Separate MR.
=> Fix prometheus problem

tolldemo/.mvn/wrapper/maven-wrapper.properties, tolldemo/HELP.md, tolldemo/pom.xml, tolldemo/src/main/java/com/example/tolldemo/TolldemoApplication.java, tolldemo/src/main/resources/application.properties, tolldemo/src/test/java/com/example/tolldemo/TolldemoApplicationTests.java
A PR to initialize the Toll application. Creates a directory and a dummy Java 11 & SB 2.9.7 application. Need to be restructured.
Will delete this branch when merged
=> Directory and dummy application

tolldemo/queue-reader/pom.xml, tolldemo/queue-reader/src/main/java/com/example/queuereader/client/AIVisionClient.java, tolldemo/queue-reader/src/main/java/com/example/queuereader/client/JournalClient.java, tolldemo/queue-reader/src/main/java/com/example/queuereader/controller/TollReaderReceiver.java, tolldemo/queue-reader/src/main/java/com/example/queuereader/model/AccountDetails.java, tolldemo/queue-reader/src/main/java/com/example/queuereader/service/AIVisionService.java, tolldemo/queue-reader/src/main/java/com/example/queuereader/service/CustomerDataService.java, tolldemo/queue-reader/src/main/java/com/example/queuereader/service/JournalService.java, tolldemo/queue-reader/src/main/resources/application.yaml
seems to work, except in rare cases where there is a duplicate license plate (d'oh)
=> tolldemo: working on the slow query

workshops/microservices-data-refactoring/dra-graph-client/pom.xml
Gets Community Detection working again
=> opg-client version to 23.4.0

docs-source/spring/content/release-notes/_index.md, docs-source/spring/content/setup/_index.md
=> Relnotes and versions

docs-source/spring/content/development/setup.md
1. Fix Oracle Database version to 23ai
2. Update pkg:maven/org.testcontainers/oracle-free@1.20.0
=> Update Docs 23ai and TestContainers version

workshops/oracleAQ/setup.sh
=> change to 23ai

workshops/oracleAQ/setup.sh
Customer bug report. Fix OCI command for sub compartments
=> Customer bug report. Fix OCI command for sub compartments

docs-source/spring/content/_index.md, docs-source/spring/content/on-premises/ol8/_index.md, docs-source/spring/content/platform/intellij-plugin/_index.md
=> Version and URL updates

docs-source/cloudbank/layouts/partials/custom-header.html
more changes to get google analytics working
and fixed issues found during that work
=> update submodule to fix build issues, and add google analytics partial

cloudbank-v4/account/src/main/resources/db/changelog/txeventq.sql, cloudbank-v4/checks/pom.xml, cloudbank-v4/pom.xml
Downgrade aqjms version and lb fix
=> Downgrade aqjms version and lb fix

cloudbank-v4/README.md, cloudbank-v4/checks/pom.xml, cloudbank-v4/checks/src/main/java/com/example/checks/ChecksApplication.java, cloudbank-v4/checks/src/main/java/com/example/checks/clients/AccountClient.java, cloudbank-v4/checks/src/main/resources/application.yaml, cloudbank-v4/pom.xml, cloudbank-v4/testrunner/pom.xml, cloudbank-v4/testrunner/src/main/java/com/example/testrunner/TestrunnerApplication.java, cloudbank-v4/testrunner/src/main/resources/application.yaml
Version upgrades and fixes for CBv4
=> Version upgrades and fixes for CBv4

.github/workflows/openjdk-base-image.yml
=> OpenJDK Image

docs-source/spring/content/development/cli/_index.md
Add doc around imagedeletebyworkload & lint
=> Add doc around imagedeletebyworkload & lint

cloudbank-v4/account/pom.xml, cloudbank-v4/account/src/main/java/com/example/accounts/AccountsApplication.java, cloudbank-v4/checks/pom.xml, cloudbank-v4/checks/src/main/java/com/example/checks/ChecksApplication.java, cloudbank-v4/common/src/main/java/com/example/common/ucp/UCPTelemetry.java, cloudbank-v4/customer/pom.xml, cloudbank-v4/customer/src/main/java/com/example/customer/CustomerApplication.java, cloudbank-v4/customer32/pom.xml, cloudbank-v4/customer32/src/main/java/com/example/customer32/Customer32Application.java, cloudbank-v4/pom.xml, cloudbank-v4/testrunner/pom.xml, cloudbank-v4/testrunner/src/main/java/com/example/testrunner/TestrunnerApplication.java
Added [opentelemetry-oracle-ucp-11.2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/oracle-ucp-11.2/library) for UCP metrics, also added a spring component to record additional UCP metrics
=> changes for enabling UCP metrics

docs-source/spring/content/infrastructure/kubernetes/_index.md
=> Namespace documentation

cloudbank-v4/customer-helidon/src/main/resources/META-INF/microprofile-config.properties
This is the final packaging that successfully booted using obaas
=> Support Liquibase

Oracle_CQRS/pom.xml
Library and Spring Boot updates
=> Library and SB updates
